spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql # mysql, oracle
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:2881/?characterEncoding=UTF-8
    username: root@test
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:/init.sql
